### ISSUE TITLE
Phenotype Patcher for Android Auto

### ISSUE THREAD

**Issue by bloodyrayne** [Eselter/AA-Phenotype-Patcher#13]
I used Phenotype Patcher for the app performance monitor, after using the patcher when I tried to connect my phone via usb cable android auto no longer works, it happens as if the car does not recognize my phone at all, I even restored the phone to factory settings but the same thing is happening again, I tried to connect my daughter's phone and it works perfectly in the car, but mine won't at all, I'm honestly very upset that I can't use it, so I'm asking for help if it's at all possible pls!!!!
I've tried everything from deleting the cache, uninstalling the Android Auto app, trying different versions, but it doesn't work.
I BEG YOU FOR HELP

**Comment by Eselter** [comment]
Try this app instead:
https://github.com/shmykelsa/AA-Tweaker
This app is discounted.
